<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ES6 Promise</title>
</head>

<body>

</body>
<script>
    /**************************************************************************************************************************
     * 1.基本语法 --- new Promise(callback(resolve, reject))
     *   promise对象是一个构造函数，用来生成Promise实例。
     *   参数为回调函数，参数里的回调函数的两个参数为成功状态和失败状态的回调函数。
     * 1.1 实例方法 Promise.prototype.方法名
     *     (1) .then(callback(res),callback(error)) 参数为成功状态和失败状态(可选)回调函数,参数res成功返回的数据,参数error成功返回的信息
     *     (2) .catch(callback(error)) 捕捉失败回调,参数error成功返回的信息。(若是在then方法里面没有写失败回调，则失败会走catch方法)
     * 
     *     (3).finally(callback(data))) --- 不管Promise最后状态如何都会执行的操作。
     * 1.2 所有Promise实例对象打印时，有两个键(key)，第一个key为状态(PromiseStatus)，第二个key为值(PromiseValue)
     **************************************************************************************************************************/
    {
        const objPromise = new Promise(function (resolve, reject) {
            // callback do something
            let res = "异步操作成功"
            if (false) {
                resolve(res)
            } else {
                reject("请求失败")
            }
        })

        console.log(objPromise);

        // then(callback(res),callback(error))
        // 参数1callback resolved是Promise对象状态为resolve的回调函数
        // 参数2callback reject是Promise对象状态为reject的回调函数
        objPromise.then(res => {
            // success
            console.log("实例then方法--成功", res)
        }, error => {
            // failure
            console.log("实例then方法--失败", error)
        }).catch(error => {
            // 若是在then方法里面没有写失败回调，则失败会走catch方法
            console.log("实例catch方法", error)
        })

        console.log("--- 在实例then()函数执行之前执行 --");
    }


    // 注意，调用resolve或reject并不会终结 Promise 的参数函数的执行
    // 一般来说，在调用resolve和reject之后Promise的使命就应该结束了。后继的操作应该放在then()方法里面。因此这个时候最好加上return语句防止还有后续错误。
    {
        new Promise((resolve, reject) => {
            return resolve("ok")
            // 使用return 之后后面的语句就不会执行了
            console.log("我是Promise调用resolve和reject函数后的操作");
        }).then(res => {
            console.log(res); // ok
        }).catch(() => {
            // 建议：可以使用catch()方法代替then()的第二个参数
            console.log(res);
        })
    }

    /**************************************************************************************************************************
     * .catch(callback(error))
     * Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。
     **************************************************************************************************************************/
    {
        const someAsyncThing = function () {
            return new Promise(function (resolve, reject) {
                // 下面一行会报错，因为x没有声明
                resolve(x + 2);
            });
        };

        someAsyncThing().then(function () {
            console.log('everything is great');
        });

        // 到那时浏览器没有终止执行，以下代码还是会输出
        setTimeout(() => {
            console.log(123)
        }, 2000);

        // Node.js 有一个unhandledRejection事件，专门监听未捕获的reject错误，
        // process.on('unhandledRejection', function (err, p) {
        //     throw err;
        // });
    }

    /**************************************************************************************************************************
     * (3)Promise.prototype.finally(callback()))
     * 不接收任何参数，无法知道Promise的状态,因此该方法内的操作应该与Promise的状态无关,不依赖执行结果
     * 
     **************************************************************************************************************************/
    {
        new Promise((resolve, reject) => {
            resolve()
        }).then().catch().finally(() => {
            console.log("finally方法");
        })
    }

    /**************************************************************************************************************************
     * 2.Promise.all()
     *   用于将多个Promise实例，包装成一个新的Promise实例
     *   参数：包含多个Promise实例的数组
     * pAll 的状态由数组内的promise实例状态决定：
     *   (1)只有数组内*所有*状态都变成resolve时 --> pAll的状态变成 resolve
     *   (2)只要由*一个*为 rejected --> pAll的状态变成 rejected ；则第一个reject的实例返回值 -> 传给pAll回调
     * 注意：
     *    若数组内单个实例有自己的catch方法，则不会触发all的catch方法。(因为执行完自己的catch之后这个实例就会变成resolve)
     **************************************************************************************************************************/
    {
        let p1 = new Promise((resolve, reject) => {
            resolve("p1-ok")
            // reject("p1-dead")
            return
        })
        let p2 = new Promise((resolve, reject) => {
            // resolve("p2-ok")
            reject("p2-dead")
            // return
        }).catch((error) => {
            // 若数组内的实例有自己的catch方法，则不会返回给pAll
            console.log("p2自己的catch"); //[p2-dead]
        })

        const pAll = Promise.all([p1, p2])
        console.log(pAll);

        pAll.then(res => {
            // 全都为resolve时才执行
            console.log(res); //["p1-ok", "p2-ok"]
        }).catch(error => {
            // 捕捉第一个reject
            console.log(error); //[p2-dead]
        })
    }

    /**************************************************************************************************************************
     * 3.Promise.race()
     *   同样返回多个实例包装成一个实例(与all含义格式相同)
     *   只要数组内有一个实例率先改变状态，pRace的状态就会改变。
     **************************************************************************************************************************/
    {

        let p1 = new Promise((resolve, reject) => {
            // resolve("race---p1-ok")
            // reject("race---p1-dead")
            return
        })
        let p2 = new Promise((resolve, reject) => {
            // resolve("race---p2-ok")
            reject("race---p2-dead")
            return
        })

        // 总是显示第一个率先改变的状态
        Promise.race([p1, p2]).then(res => {
            console.log(res); //["p1-ok", "p2-ok"]
        }).catch(error => {
            console.log(error); //[p2-dead]
        })
    }

    /**************************************************************************************************************************
     * 4.Promise.allSettled()
     *   (与all含义格式相同)
     *   只有所有这些参数实例都返回结果(不管什么状态) --> 才执行总的返回(ES2020引入) 
     *   场景：有时候我们不关心异步操作的结果，只关心这些操作有没有结束。这时，Promise.allSettled()方法就很有用。
     **************************************************************************************************************************/
    {}

    /**************************************************************************************************************************
     * 提案：
     * 5.Promise.any()
     *   (与all含义格式相同)
     *   只要参数实例有一个变成fulfilled状态，包装实例就会变成fulfilled状态；如果所有参数实例都变成rejected状态，包装实例就会变成rejected状态。
     * 8.Promise.try()
     *   让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API 
     *   事实上，Promise.try就是模拟try代码块，就像promise.catch模拟的是catch代码块。
     **************************************************************************************************************************/

    /**************************************************************************************************************************
     * 6.Promise.resolve()
     *   将现有对象转为 Promise 对象。
     * 参数情况：
     *   (1) 是一个Promise对象，--> 原封不动返回
     *   (2) 是一个thenable对象(指该对象有then方法) --> 转为Promise对象，然后立即执行该对象的then方法
     *   (3) 参数不是具有then方法的对象，或者根本不是对象 --> 返回一个resolved状态的新的Promise对象
     *   (4) 不带有任何参数 --> 返回一个resolved状态的Promise对象 ---- 如果希望得到一个Promise对象，比较方便的方法就是直接调用该方法)
     **************************************************************************************************************************/
    {
        // 参数情况(1)
        let p1 = new Promise((resolve) => {})
        let param1 = Promise.resolve(p1)
        console.log(param1);

        // 参数情况(2)
        let p2 = {
            then: (resolve) => {
                resolve("对象具有then方法")
            }
        }
        Promise.resolve(p2).then((res) => {
            console.log(res); // 对象具有then方法
        })

        // 参数情况(3)
        let p3 = Promise.resolve("hello")
        console.log(p3); // Promise {<resolved>: hello}  //对象内第一个键为状态，第二个为值

        // 参数情况(4)
        let p4 = Promise.resolve()
        console.log(p4); // Promise {<resolved>: undefined}
    }

    /**************************************************************************************************************************
     * 7.Promise.reject()
     *   含义参数等与Promise.resolve()类似，只不过返回的状态为rejected
     *   注意: Promise.reject()方法的参数，会原封不动地作为reject的理由
     **************************************************************************************************************************/
    {
        // 参数情况(1)
        let p1 = new Promise((reject) => {})
        let param1 = Promise.reject(p1).catch(() => {}) //此时必须有catch方法  || 报错
        console.log(param1);

        // 参数情况(2)
        let p2 = {
            then: (reject) => {
                reject("对象具有then方法")
            }
        }
        Promise.reject(p2).then().catch((error) => {
            // 注意注意：此时的 error === p2
            console.log("Promise.reject() ------ ", error);
        })

        // 参数情况(3)
        let p3 = Promise.reject("hello")
        console.log(p3); // Promise {<rejected>: "hello"}  还未执行catch因此状态为rejected
        p3.catch(() => {})

        // 参数情况(4)
        let p4 = Promise.reject().catch(() => {})
        console.log(p4); // Promise {<resolved>: undefined} 因为执行了catch之后状态变为resolved
    }
</script>

<script>
    // ********************************************************************* 测试 ********************************************************************* //

    let async_res = async_fun()

    async function async_fun() {
        // const p1 = await a_get_pro("string").catch((e) => {})
        const p1 = await a_get_pro("string")
        if (p1) {
            return console.log("await a_get_pro返回值true", p1);
        }
        return console.log("await a_get_pro返回值false", p1);
    }

    function a_get_pro(arg) {
        return new Promise((resolve, reject) => {
            if (window.a) {
                return resolve(true)
            }
            return reject(false)
        }).catch((e) => {})
    }

    console.log("sjsi ");
</script>


</html>